export const DRIVE_REQUEST_HEADERS = [
  "Request ID",
  "Company",
  "Type",
  "Eligible Pool",
  "CGPA Cutoff",
  "PPT Datetime",
  "OT Datetime",
  "Interview Datetime",
  "PPT Status",
  "OT Status",
  "INTERVIEW Status",
  "PPT Suggested Datetime",
  "OT Suggested Datetime",
  "INTERVIEW Suggested Datetime",
  "Internship Stipend",
  "FTE CTC",
  "FTE Base",
  "Expected Hires",
  "Drive Status",
  "Created At",
];

export const COMPANY_DRIVES_HEADERS = [
  "Company",
  "Request ID",
  "Type",
  "Eligible Pool",
  "CGPA Cutoff",
  "PPT Datetime",
  "OT Datetime",
  "Interview Datetime",
  "PPT Status",
  "OT Status",
  "INTERVIEW Status",
  "Internship Stipend",
  "FTE CTC",
  "FTE Base",
  "Expected Hires",
  "Drive Status",
  "Results Published",
  "Results Published At",
  "Last Updated",
];
