export const DRIVE_REQUEST_HEADERS = [
  "Request ID",
  "Company",
  "SPOC",
  "Type",
  "Eligible Pool",
  "CGPA Cutoff",
  "PPT Datetime",
  "OT Datetime",
  "Interview Datetime",
  "PPT Status",
  "OT Status",
  "INTERVIEW Status",
  "PPT Suggested Datetime",
  "OT Suggested Datetime",
  "INTERVIEW Suggested Datetime",
  "Internship Stipend",
  "FTE CTC",
  "FTE Base",
  "Expected Hires",
  "Drive Status",
  "Created At",
];

export const COMPANY_DRIVES_HEADERS = [
  "Company",
  "SPOC",
  "Request ID",
  "Type",
  "Eligible Pool",
  "CGPA Cutoff",
  "PPT Datetime",
  "OT Datetime",
  "Interview Datetime",
  "PPT Status",
  "OT Status",
  "INTERVIEW Status",
  "Internship Stipend",
  "FTE CTC",
  "FTE Base",
  "Expected Hires",
  "Drive Status",
  "Results Published",
  "Results Published At",
  "Last Updated",
];

export const SHEET_TEMPLATES = {
  students: [
    "Roll No",
    "Name",
    "Gender",
    "Branch",
    "CGPA",
    "Eligible",
    "Placement Status",
    "Placement Type",
    "Company",
    "CTC",
    "Offer Revoked",
  ],

  offers: [
    "Roll No",
    "Company",
    "Offer Type",
    "CTC (LPA)",
    "Offer Status",
  ],

  companyDrives: [
    "Company",
    "SPOC",
    "Request ID",
    "Drive Type",
    "Eligible Pool",
    "PPT Datetime",
    "OT Datetime",
    "Interview Datetime",
    "PPT Status",
    "OT Status",
    "INTERVIEW Status",
    "Internship Stipend",
    "FTE CTC",
    "FTE Base",
    "Expected Hires",
    "Actual Hires",
    "Drive Status",
    "Results Published",
    "Results Published At",
    "Last Updated",
  ],

  placementStats: ["Metric", "Value"],

  ctcDistribution: ["CTC Threshold", "Number of Students"],

  overall: [
    "Branch",
    "Total Students",
    "Total Male Students",
    "Total Female Students",
    "Total Eligible",
    "Total Male Eligible",
    "Total Female Eligible",
    "Total Placed",
    "No of Male Placed",
    "No of Female Placed",
    "% Students Placed (of Total)",
    "% Students Placed (of Eligible)",
    "% Male Placed (of Total)",
    "% Male Placed (of Eligible)",
    "% Female Placed (of Total)",
    "% Female Placed (of Eligible)",
    "Highest CTC",
    "Average CTC",
    "Lowest CTC",
    "Median CTC",
    "Only Internship Offers",
    "Only FTE Offers",
    "Both Offers",
    "Unplaced (CGPA >= 8)",
    "Unplaced (CGPA >= 7.5)",
    "Unplaced (CGPA >= 7)",
    "Unplaced (CGPA >= 6.5)",
  ],
};